### ISSUE TITLE
Classe AsyncOverlay

### ISSUE THREAD

**Issue by ClaraMaia2** [lleoserrano/asyncstate#12]
Depois de ver a aula do Flutter Experience dessa semana, estava desenvolvendo o código do arquivo lab_clinicas_loader.dart que usava o package asyncstate. Ele está tentando fazer um 'extend' de uma classe dentro do asyncstate.dart que eu não consegui achar (AsyncOverlay). 
Com isso, está dando este erro: 
![Captura de tela 2024-01-30 215751](https://github.com/DevLSerrano/asyncstate/assets/102636646/b9a5b376-3b61-4a34-a6e2-e9e00e200af9)
Como devo continuar?

**Comment by lleoserrano** [comment]
É preciso verificar os imports do arquivo e até mesmo a configuração no pubspec.yaml, existe algum outro importe neste arquivo?

**Comment by ClaraMaia2** [comment]
Meus imports são esses:

![Captura de tela 2024-01-31 111449](https://github.com/DevLSerrano/asyncstate/assets/102636646/5a670248-997f-42d8-8318-1ed8eb404037)

E as configurações do pubspec.yaml são:

![Captura de tela 2024-01-31 111638](https://github.com/DevLSerrano/asyncstate/assets/102636646/1c91a878-7669-4072-95b5-a35b861127d3)

**Comment by lleoserrano** [comment]
A versão do asynctate no "pubspec.yaml" está incorreta, a versão dev é `asyncstate: ^2.1.1-dev.1`.

**Comment by ClaraMaia2** [comment]
Ah muito obrigada!!
